<a href="https://colab.research.google.com/github/Nilofar87/Nilo_Repo/blob/main/numpy_prctc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+1

3

In [2]:
import numpy as np

In [6]:
one = np.array([1,2,3,4,5])

In [7]:
np.ndim(one)

1

In [8]:
two = np.array([[1,2,3],[7,8,9]])

In [9]:
two

array([[1, 2, 3],
       [7, 8, 9]])

In [10]:
np.ndim(two)

2

In [12]:
three = np.array([[[10,20,30,40],[50,60,70,80]],[[11,22,33,44],[55,66,77,88]]])

In [14]:
three

array([[[10, 20, 30, 40],
        [50, 60, 70, 80]],

       [[11, 22, 33, 44],
        [55, 66, 77, 88]]])

In [13]:
np.ndim(three)

3

In [17]:
arr = np.array([11,22,3.5,'apple','banana'])

In [19]:
arr

array(['11', '22', '3.5', 'apple', 'banana'], dtype='<U32')

In [18]:
np.ndim(arr)

1

In [22]:
# array allows methematical operations

a=np.array([2,5,7,9,10])

a/2

array([1. , 2.5, 3.5, 4.5, 5. ])

In [23]:
print(a/5)

[0.4 1.  1.4 1.8 2. ]
